name: Run main.py daily

on:
  schedule:
    - cron: '0 3 * * *'  # اجرای روزانه ساعت ۳ صبح UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install persiantools

    - name: Run main.py
      env:
        AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }}
      run: python main.py
